apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: 113222697619.dkr.ecr.us-east-1.amazonaws.com/clo835-app
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "172.17.0.2"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "pw"
    - name: APP_COLOR
      value: "blue"